version: '3.8'
name: scraper
services:
  web:
    image: 'scraper'
    container_name: 'scraper_api'
    restart: always
    build:
      target: production
    ports:
      - 4200:4200
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #     reservations:
    #       memory: 256M
    volumes:
      - ./api:/app/api
      - ./index.js:/app/index.js
      - ./package.json:/app/package.json
    stdin_open: true
    tty: true
    env_file:
      - .env
